[manifest]
version = "1.0.0"
dump_lua = true
priority = 50

# disable buttons
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = '''if G.GAME.modifiers.no_blind_reward and G.GAME.modifiers.no_blind_reward[self:get_type()] then self.dollars = 0 end'''
position = 'before'
payload = '''if G.GAME.modifiers.synthb_blind_reward_mod then self.dollars = self.dollars + G.GAME.modifiers.synthb_blind_reward_mod end'''
match_indent = true




