[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# massive thanks to ElleJokers

# Add debug give for characters
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = 'if key == "3" then'
position = "after"
payload = '''
if _card.ability.set == 'synthb_Character' and G.synthb_character_area then
    SMODS.add_card({area = G.synthb_character_area, key = _card.config.center.key})
    _card:set_sprites(_card.config.center)
end
'''
match_indent = true

# Add character calculation
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = "after"
payload = '''
table.insert(t,1,G.synthb_character_area)
'''
match_indent = true

# Add characters appearing in shop
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "for _,v in ipairs(SMODS.ConsumableType.obj_buffer) do"
position = "before"
payload = 'total_rate = total_rate + G.GAME.synthb_character_rate'
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "for _, v in ipairs(rates) do"
position = "before"
payload = "table.insert(rates, {type = 'synthb_Character', val = G.GAME.synthb_character_rate})"
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils/weights.lua"]'
pattern = "for _,v in ipairs(SMODS.ConsumableType.obj_buffer) do"
position = "before"
payload = "args.types[#args.types + 1] = 'synthb_Character'"
match_indent = true

# Put characters in the correct area when buying from the shop
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.jokers:emplace(c1)"
position = 'at'
payload = '''
if c1.ability.set == "synthb_Character" then
    G.synthb_character_area:emplace(c1)
else
    G.jokers:emplace(c1)
end
'''
match_indent = true

# Let characters get debuffed by blinds
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "--add new debuffs"
position = 'after'
payload = '''
for _, v in ipairs(G.synthb_character_area.cards) do
    if not reset then self:debuff_card(v, true) end
end
'''
match_indent = true

# draw cards in custom card area
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "if self.config.type == 'joker' or self.config.type == 'consumeable' or self.config.type == 'shop' or self.config.type == 'title_2' then "
position = 'at'
payload = '''if self.config.type == 'joker' or self.config.type == 'consumeable' or self.config.type == 'shop' or self.config.type == 'title_2' or self.config.type == "characters" then '''
match_indent = true

# highlight cards in custom card area
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "elseif self.config.type == 'joker' or self.config.type == 'consumeable' then"
position = 'at'
payload = '''elseif self.config.type == 'joker' or self.config.type == 'consumeable' or self.config.type == "characters" then'''
match_indent = true


# sell buttons
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.consumeable or self.ability.set == 'Joker' or (self.area and self.area == G.pack_cards) then"
position = 'at'
payload = '''if self.ability.consumeable or self.ability.set == 'Joker' or (self.area and self.area == G.pack_cards) or self.ability.set == "synthb_Character" then'''
match_indent = true

# sell  buttons
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.consumeable or self.ability.set == 'Joker' then"
position = 'at'
payload = '''if self.ability.consumeable or self.ability.set == 'Joker' or self.ability.set == "synthb_Character" then'''
match_indent = true

# force popup to the left if its tiny

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''local popup_direction = (self.children.buy_button or (self.area and self.area.config.view_deck) or (self.area and self.area.config.type == 'shop')) and 'cl' or
							(self.T.y > G.CARD_H*0.8 and self.T.y < G.CARD_H*1.8) and ((self.T.x > G.ROOM.T.w*0.4) and "cl" or "cr") or
							(self.T.y < G.CARD_H*0.8) and 'bm' or
							'tm''''
position = "after"
payload = "popup_direction = (self.area and self.area.config.type == 'characters') and 'bl' or popup_direction"
match_indent = true
