[manifest]
version = "1.0.0"
dump_lua = true
priority = 50


# delay scoring if theres blackjack to play
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''check_for_unlock({type = 'hand_contents', cards = G.play.cards})'''
position = 'before'
payload = '''if SynthB.Globals.blackjacks_to_play > 0 then return false end'''
match_indent = true