[manifest]
version = "1.0.0"
dump_lua = true
priority = 50

# disable buttons
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''config = {align='tmi', offset = {x=0,y=G.ROOM.T.y+11},major = G.hand, bond = 'Weak'}
        }'''
position = 'after'
payload = '''
G.synthb_gacha_banner = UIBox{
	definition = G.UIDEF.synthb_create_gacha_banner(),
	config = {
		offset = {x = 0, y = 0.05},
		major = G.shop,
		bond = "Strong",
		align = "tri"
	}
}
local shop_index
for i, box in ipairs(G.I.UIBOX) do
	if box == G.shop then
		shop_index = i
	end
	if box == G.synthb_gacha_banner then
		if shop_index then
			G.I.UIBOX[shop_index] = box
			G.I.UIBOX[i] = G.shop
		end
	end
end
'''
match_indent = true


# disable buttons
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''}))
          G.STATE_COMPLETE = true'''
position = 'after'
payload = '''
delay(2)
G.E_MANAGER:add_event(Event{
	func = function()
		G.synthb_gacha_banner.alignment.offset.x = 2.8
		return true
	end
})
'''
match_indent = true


# return to shop after synthb_gacha_banner
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''prev_state == G.STATES.BUFFOON_PACK) and G.booster_pack then'''
position = 'before'
payload = '''prev_state == G.STATES.SYNTHB_GACHA_BANNER or'''
match_indent = true



# add card to character area
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''elseif card.ability.set == 'Joker' then 
      card:add_to_deck()
      G.jokers:emplace(card)
      play_sound('card1', 0.8, 0.6)
      play_sound('generic1')
      dont_dissolve = true
      delay_fac = 0.2'''
position = 'before'
payload = '''elseif card.ability.set == 'synthb_Character' then 
			if G.FUNCS.check_for_buy_space(card) then
				card:add_to_deck()
				G.synthb_character_area:emplace(card)
				play_sound('card1', 0.8, 0.6)
				play_sound('generic1')
				dont_dissolve = true
				delay_fac = 0.2
			else return end
			'''
match_indent = true

# return to shop after synthb_gacha_banner
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''(G.STATE == G.STATES.BUFFOON_PACK and G.STATES.BUFFOON_PACK) or'''
position = 'before'
payload = '''(G.STATE == G.STATES.SYNTHB_GACHA_BANNER and G.STATES.SYNTHB_GACHA_BANNER) or'''
match_indent = true


